from tels_analysis import colocalization_analysis

fileList = ["BFV2AA", "BFV2AB", "BFV2AC", "BFV2AMA", "BFV2AMB", "BFV2AMC", "BFV2MA", "BFV2MB", "BFV2MC",
			"BFV2NEGA", "BFV2NEGAM", "BFV2NEGM", "BFXTAA", "BFXTAB", "BFXTAC", "BFXTAMA", "BFXTAMB", "BFXTAMC"
			"BFXTMA", "BFXTMB", "BFXTMC", "BFXTNEGA", "BFXTNEGAM", "BFXTNEGM", "HFV2AA", "HFV2AB", "HFV2AC",
			"HFV2AMA", "HFV2AMB", "HFV2AMC", "HFV2MA", "HFV2MB", "HFV2MC", "HFV2NEGA", "HFV2NEGAM", "HFV2NEGM",
			"HFXTAA", "HFXTAB", "HFXTAC", "HFXTAMA", "HFXTAMB", "HFXTAMC", "HFXTMA", "HFXTMB", "HFXTMC",
			"HFXTNEGA", "HFXTNEGAM", "HFXTNEGM", "MOV2AA", "MOV2AB", "MOV2AC", "MOV2AMB", "MOV2MA", "MOV2MB",
			"MOV2MC", "MOV2NEGA", "MOV2NEGAM", "MOV2NEGM", "MOXTAA", "MOXTAB", "MOXTAC", "MOXTAMA", "MOXTAMB",
			"MOXTAMC", "MOXTMA", "MOXTMB", "MOXTMC", "MOXTNEGA", "MOXTNEGAM", "MOXTNEGM", "SV2AA", "SV2AB",
			"SV2AC", "SV2AMA", "SV2AMB", "SV2AMC", "SV2MA", "SV2MB", "SV2MC", "SV2NEGA", "SV2NEGAM", "SV2NEGM",
			"SXTAA", "SXTAB", "SXTAC", "SXTAMA", "SXTAMB", "SXTAMC", "SXTMA", "SXTMB", "SXTMC", "SXTNEGA",
			"SXTNEGAM", "SXTNEGM"]

